<a href="https://colab.research.google.com/github/a151815058/Standardzation_test/blob/main/Standardzation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


### Z-score

#### import package

In [ ]:
import numpy as np
from scipy import stats

In [ ]:
data = np.array([200,300,400,600,1000])
data

array([ 200,  300,  400,  600, 1000])

In [ ]:
data.shape

(5,)

In [ ]:
type(data)

numpy.ndarray

In [ ]:
zscore = stats.zscore(data)
zscore

array([-1.06066017, -0.70710678, -0.35355339,  0.35355339,  1.76776695])

### Min-Max

#### import package

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
data2=np.array([[200],[300],[400],[600],[1000]])
data2

array([[ 200],
       [ 300],
       [ 400],
       [ 600],
       [1000]])

In [ ]:
data2.shape

(5, 1)

In [ ]:
minmax = scaler.fit_transform(data2)
minmax

array([[0.   ],
       [0.125],
       [0.25 ],
       [0.5  ],
       [1.   ]])

In [ ]:
from keras.datasets import mnist
import cv2
(x_train,y_train),(x_text,y_test) = mnist.load_data()

In [ ]:
x_train.shape

(60000, 28, 28)